### ISSUE TITLE
Gateway（32bit）、キャッシュサイズが2GB超で落ちる

### ISSUE THREAD

**Issue by lamatsujun** [suzumura-ss/castoro#58]
## TODO
- 32bit Gateway の調査
- 改修対応

**Comment by lamatsujun** [comment]
### テストスクリプト

#### テストスクリプト for 0.1.1

<pre><code class="ruby">#!/usr/bin/env ruby

if ARGV[0].to_s.empty?
  puts
  puts "Usage: #{$0} PAGES"
  puts
  exit 1
end

def memory_usage()
  rss = -1
  open('/proc/self/status').each { |line|
    if line =~ /^VmRSS:/
      line.gsub!(/.*:\s*(\d+).*/, '\1')
      return line.to_i / 1024.0
    end
  }
  rss
end

gem 'castoro-gateway', '0.1.1'
require 'castoro-gateway/cache'

include Castoro

page      = ARGV[0].to_i
page_size = page

printf("Ruby     : %s\n", RUBY_VERSION)
printf("Pages    : %d\n", page)

GC.start
smem  = memory_usage
stime = Time.now
cache = Cache.new(page_size)
emem  = memory_usage
etime = Time.now
GC.start

printf("Time     : %.3f sec.\n", etime - stime)
printf("Usage    : %.3f MByte\n", emem - smem)
</code></pre>


#### テストスクリプト for 0.2.0.pre

<pre><code class="ruby">#!/usr/bin/env ruby

if ARGV[0].to_s.empty?
  puts
  puts "Usage: #{$0} PAGES"
  puts
  exit 1
end

def memory_usage()
  rss = -1
  open('/proc/self/status').each { |line|
    if line =~ /^VmRSS:/
      line.gsub!(/.*:\s*(\d+).*/, '\1')
      return line.to_i / 1024.0
    end
  }
  rss
end

gem 'castoro-gateway', '0.2.0.pre'
require 'castoro-gateway/cache'

include Castoro

page      = ARGV[0].to_i
page_size = page

printf("Ruby     : %s\n", RUBY_VERSION)
printf("Pages    : %d\n", page)

GC.start
smem  = memory_usage
stime = Time.now
cache = Cache.new(page_size)
emem  = memory_usage
etime = Time.now
GC.start

printf("Time     : %.3f sec.\n", etime - stime)
printf("Usage    : %.3f MByte\n", emem - smem)
</code></pre>

**Comment by lamatsujun** [comment]
### 実行結果

#### CPU 32bit Mem 8GB for 0.1.1

<pre>
$ cat /etc/redhat-release
CentOS release 5.6 (Final)
$ uname -a
Linux localhost.localdomain 2.6.18-238.el5PAE #1 SMP Thu Jan 13 17:10:20 EST 2011 i686 i686 i386 GNU/Linux
$ free -m
             total       used       free     shared    buffers     cached
Mem:          8104       1624       6480          0         52       1443
-/+ buffers/cache:        128       7976
Swap:         5023          0       5023
$ ./gateway-memory-test-0.1.sh `expr 32765 \* 1`
Ruby     : 1.9.2
Pages    : 32765
Time     : 2.207 sec.
Usage    : 896.465 MByte
$ ./gateway-memory-test-0.1.sh `expr 32765 \* 2`
Ruby     : 1.9.2
Pages    : 65530
Time     : 7.841 sec.
Usage    : 1793.133 MByte
$ ./gateway-memory-test-0.1.sh `expr 32765 \* 3`
Ruby     : 1.9.2
Pages    : 98295
Time     : 11.773 sec.
Usage    : 2689.676 MByte
$ ./gateway-memory-test-0.1.sh `expr 32765 \* 4`
Ruby     : 1.9.2
Pages    : 131060
terminate called after throwing an instance of 'std::bad_alloc'
  what():  St9bad_alloc
アボートしました
</pre>


#### CPU 32bit Mem 8GB for 0.2.0.pre

<pre>
$ cat /etc/redhat-release
CentOS release 5.6 (Final)
$ uname -a
Linux localhost.localdomain 2.6.18-238.el5PAE #1 SMP Thu Jan 13 17:10:20 EST 2011 i686 i686 i386 GNU/Linux
$ free -m
             total       used       free     shared    buffers     cached
Mem:          8104       1624       6480          0         52       1443
-/+ buffers/cache:        128       7976
Swap:         5023          0       5023
$ ./gateway-memory-test.sh `expr 32768 \* 1`
Ruby     : 1.9.2
Pages    : 32768
Time     : 3.952 sec.
Usage    : 896.688 MByte
$ ./gateway-memory-test.sh `expr 32768 \* 2`
Ruby     : 1.9.2
Pages    : 65536
Time     : 7.870 sec.
Usage    : 1793.312 MByte
$ ./gateway-memory-test.sh `expr 32768 \* 3`
Ruby     : 1.9.2
Pages    : 98304
Time     : 11.807 sec.
Usage    : 2689.938 MByte
$ ./gateway-memory-test.sh `expr 32768 \* 4`
Ruby     : 1.9.2
Pages    : 131072
terminate called after throwing an instance of 'std::bad_alloc'
  what():  St9bad_alloc
アボートしました
</pre>

**Comment by lamatsujun** [comment]
### 実行結果

#### CPU 64bit Mem 6GB for 0.1.1

<pre>
$ cat /etc/redhat-release
CentOS release 6.2 (Final)
$ uname -a
Linux localhost.localdomain 2.6.32-220.el6.x86_64 #1 SMP Tue Dec 6 19:48:22 GMT 2011 x86_64 x86_64 x86_64 GNU/Linux
$ free -m
             total       used       free     shared    buffers     cached
Mem:          5853        154       5699          0          3         21
-/+ buffers/cache:        128       5724
Swap:          991         13        978
$ ./gateway-memory-test-0.1.sh `expr 32768 \* 1`
Ruby     : 1.9.2
Pages    : 32768
Time     : 2.300 sec.
Usage    : 897.332 MByte
$ ./gateway-memory-test-0.1.sh `expr 32768 \* 2`
Ruby     : 1.9.2
Pages    : 65536
Time     : 7.985 sec.
Usage    : 1794.582 MByte
$ ./gateway-memory-test-0.1.sh `expr 32768 \* 3`
Ruby     : 1.9.2
Pages    : 98304
Time     : 8.041 sec.
Usage    : 2691.832 MByte
$ ./gateway-memory-test-0.1.sh `expr 32768 \* 4`
Ruby     : 1.9.2
Pages    : 131072
Time     : 15.788 sec.
Usage    : 3589.086 MByte
$ ./gateway-memory-test-0.1.sh `expr 32768 \* 5`
Ruby     : 1.9.2
Pages    : 163840
Time     : 14.045 sec.
Usage    : 4486.344 MByte
$ ./gateway-memory-test-0.1.sh `expr 32768 \* 6`
Ruby     : 1.9.2
Pages    : 196608
Time     : 17.137 sec.
Usage    : 5383.594 MByte
$ ./gateway-memory-test-0.1.sh `expr 32768 \* 7`
Ruby     : 1.9.2
Pages    : 229376
Time     : 33.857 sec.
Usage    : 5525.691 MByte
$ ./gateway-memory-test-0.1.sh `expr 32768 \* 8`
Ruby     : 1.9.2
Pages    : 262144
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
アボートしました (コアダンプ)
</pre>


#### CPU 64bit Mem 6GB for 0.2.0.pre

<pre>
$ cat /etc/redhat-release
CentOS release 6.2 (Final)
$ uname -a
Linux localhost.localdomain 2.6.32-220.el6.x86_64 #1 SMP Tue Dec 6 19:48:22 GMT 2011 x86_64 x86_64 x86_64 GNU/Linux
$ free -m
             total       used       free     shared    buffers     cached
Mem:          5853        154       5699          0          3         21
-/+ buffers/cache:        128       5724
Swap:          991         13        978
$ ./gateway-memory-test.sh `expr 32768 \* 1`
Ruby     : 1.9.2
Pages    : 32768
Time     : 10.773 sec.
Usage    : 897.316 MByte
$ ./gateway-memory-test.sh `expr 32768 \* 2`
Ruby     : 1.9.2
Pages    : 65535
Time     : 14.960 sec.
Usage    : 1794.535 MByte
$ ./gateway-memory-test.sh `expr 32768 \* 3`
Ruby     : 1.9.2
Pages    : 98304
Time     : 18.751 sec.
Usage    : 2691.828 MByte
$ ./gateway-memory-test.sh `expr 32768 \* 4`
Ruby     : 1.9.2
Pages    : 131072
Time     : 21.522 sec.
Usage    : 3589.078 MByte
$ ./gateway-memory-test.sh `expr 32768 \* 5`
Ruby     : 1.9.2
Pages    : 163840
Time     : 26.308 sec.
Usage    : 4486.457 MByte
$ ./gateway-memory-test.sh `expr 32768 \* 6`
Ruby     : 1.9.2
Pages    : 196608
Time     : 17.987 sec.
Usage    : 5383.582 MByte
$ ./gateway-memory-test.sh `expr 32768 \* 7`
Ruby     : 1.9.2
Pages    : 229376
Time     : 28.946 sec.
Usage    : 5517.484 MByte
$ ./gateway-memory-test.sh `expr 32768 \* 8`
Ruby     : 1.9.2
Pages    : 262144
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
アボートしました (コアダンプ)
</pre>

**Comment by hamajyotan** [comment]
以下 2つの起動方法でメモリ使用量に差異はある。
- Gateway プロセスとして実行
- キャッシュクラスだけインスタンスを生成

差異はキャッシュ以外のインスタンスが確保するメモリ使用量によるものと思われる。

**Comment by lamatsujun** [comment]
### 100000 キャッシュページを超えたあたりから落ちる

#### 動く

```
sakaguchi:
  <<: *default
  user: sakaguchi
  workers: 5
  cache:
    cache_size: <%= Castoro::Cache::PAGE_SIZE * 100000 %>
```

#### 動く

```
sakaguchi:
  <<: *default
  user: sakaguchi
  workers: 2
  cache:
#    cache_size: <%= 3.05*1024*1024*1024 %>
#    cache_size: 3300000000
#    cache_size: 3342500000
#    cache_size: <%= Castoro::Cache::PAGE_SIZE * 100000 %>
    cache_size: <%= Castoro::Cache::PAGE_SIZE * 101650 %>
#    cache_size: <%= Castoro::Cache::PAGE_SIZE * 101660 %>
```

#### 動かない

ワーカの数を増やした

```
sakaguchi:
  <<: *default
  user: sakaguchi
  workers: 5
  cache:
#    cache_size: <%= 3.05*1024*1024*1024 %>
#    cache_size: 3300000000
#    cache_size: 3342500000
#    cache_size: <%= Castoro::Cache::PAGE_SIZE * 100000 %>
    cache_size: <%= Castoro::Cache::PAGE_SIZE * 101650 %>
#    cache_size: <%= Castoro::Cache::PAGE_SIZE * 101660 %>
```
